# EDIT THIS FILE

# to connect the the snowflakeClient API, copy this file in the .config folder and remove
# the `_template` filename ending.
# the resulting file should be named snowflake_credentials.toml
#! DO NOT COMMIT the created file containing the credentials.
#! it is excluded by default in the .gitignore.
# use the snowflakeClient username  & password provided to you
# by Fabric.

username = 'hagaiy' # insert username here as a string
password = 'Fabric2023' # insert password here as a string