name: Sync alerts
on:
  push:
    paths:
      - 'alerts/**'
    branches: [main]
jobs:
  sync-alerts:
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.docker_meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: sync-rules
        uses: grafana/cortex-rules-action@v0.8.0
        env:
          CORTEX_ADDRESS: https://prometheus-us-central1.grafana.net
          CORTEX_TENANT_ID: 22258
          CORTEX_API_KEY: ${{ secrets.ORG_CORTEX_API_KEY }}
          ACTION: sync
          RULES_DIR: "./alerts/"
          NAMESPACES: dashflake